// Generated by scripts/build-geo.ts. Do not edit by hand.
//
// Maps each doc page's URL slug (the `$` splat, e.g. "guide/basic") to
// that page's own title, taken from its `title:` frontmatter or first
// `# H1`. The /form/$ and /store/$ routes read this for a real per-page
// <title>; see src/lib/seo.ts.

export const docTitles: {
  form: Record<string, string>;
  store: Record<string, string>;
} = {
  "form": {
    "guide": "Why Kin Form?",
    "guide/getting-started": "Getting Started",
    "guide/concepts": "Concepts",
    "guide/basic": "A Basic Form",
    "guide/faq": "FAQ & Non-Goals",
    "guide/per-node-validation": "Per-node Validation",
    "guide/schema-validation": "Schema Validation",
    "guide/linked-fields": "Linked Fields",
    "guide/listeners": "Listeners",
    "guide/nested-objects": "Nested Objects",
    "guide/dynamic-arrays": "Dynamic Arrays",
    "guide/flat-vs-nested": "Flat vs. Nested Structure",
    "guide/dirty-tracking-and-reset": "Dirty Tracking & Reset",
    "guide/submission-handling": "Submission Handling",
    "guide/async-initial-values": "Async Initial Values",
    "guide/reactivity": "Reactivity",
    "guide/form-composition": "Form Composition",
    "guide/multistep": "Multistep Forms",
    "guide/devtools": "DevTools",
    "guide/ssr": "Server-Side Rendering (SSR)",
    "guide/common-pitfalls": "Common Pitfalls",
    "guide/shadcn-ui": "shadcn/ui Integration",
    "validators": "Built-in Validators",
    "comparison": "Comparison Overview",
    "comparison/react-hook-form": "vs React Hook Form",
    "comparison/tanstack-form": "vs TanStack Form",
  },
  "store": {
    "guide": "Why Kin Store?",
    "guide/getting-started": "Getting Started",
    "guide/design-principles": "Design Principles",
    "guide/faq": "FAQ & Non-Goals",
    "guide/create-store": "createStore",
    "guide/with-plugins": "withPlugins",
    "guide/derive": "derive",
    "guide/writing-plugins": "Writing Plugins",
    "comparison": "Comparison",
    "plugins": "Official Plugins",
    "plugins/broadcast": "broadcast",
    "plugins/devtools": "devtools",
    "plugins/history": "history",
    "plugins/immer": "immer",
    "plugins/persist": "persist",
    "react": "React Bindings",
    "examples": "Guided Examples",
    "examples/nextjs": "Next.js SSR",
    "examples/tanstack-query-fat-store": "TanStack Query and One Fat Store",
    "examples/tanstack-query-primitive-stores":
      "TanStack Query and Primitive Stores",
    "examples/cross-tab-sync": "Cross-Tab Sync",
  },
};
