/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormSplatRouteImport } from './routes/form/$'
import { Route as StoreSplatRouteImport } from './routes/store/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormSplatRoute = FormSplatRouteImport.update({
  id: '/form/$',
  path: '/form/$',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreSplatRoute = StoreSplatRouteImport.update({
  id: '/store/$',
  path: '/store/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/form/$': typeof FormSplatRoute
  '/store/$': typeof StoreSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/form/$': typeof FormSplatRoute
  '/store/$': typeof StoreSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/form/$': typeof FormSplatRoute
  '/store/$': typeof StoreSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/form/$' | '/store/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/form/$' | '/store/$'
  id: '__root__' | '/' | '/form/$' | '/store/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormSplatRoute: typeof FormSplatRoute
  StoreSplatRoute: typeof StoreSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form/$': {
      id: '/form/$'
      path: '/form/$'
      fullPath: '/form/$'
      preLoaderRoute: typeof FormSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$': {
      id: '/store/$'
      path: '/store/$'
      fullPath: '/store/$'
      preLoaderRoute: typeof StoreSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormSplatRoute: FormSplatRoute,
  StoreSplatRoute: StoreSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
